name       : ruby-net-ssh
version    : 5.2.0
release    : 6
source     :
    - https://rubygems.org/downloads/net-ssh-5.2.0.gem : 80a8a71d39e9f917ed265f66c0c5985f1849fc5e7156ac48f14dd1d4af683c80
license    : MIT
component  : programming.ruby
summary    : RubyGem - net-ssh
description: |
    Net::SSH: a pure-Ruby implementation of the SSH2 client protocol. It allows you to write programs that invoke and interact with processes on remote servers, via SSH2.
builddeps  :
    - pkgconfig(ruby-2.7)
rundeps    :
    - ruby
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
