name       : ruby-net-ssh
version    : 5.1.0
release    : 4
source     :
    - https://rubygems.org/downloads/net-ssh-5.1.0.gem : f61c78a0c98910b91a7c4ba6f147fd6870d8349f26a7008a8e86d3dd3372f449
license    : MIT
component  : programming.ruby
summary    : RubyGem - net-ssh
description: |
    Net::SSH: a pure-Ruby implementation of the SSH2 client protocol. It allows you to write programs that invoke and interact with processes on remote servers, via SSH2.
builddeps  :
    - pkgconfig(ruby-2.6)
rundeps    :
    - ruby
install    : |
    %gem_install
