name       : ruby-net-ssh
version    : 5.0.2
release    : 2
source     :
    - https://rubygems.org/downloads/net-ssh-5.0.2.gem : 8863d89c55805ee27d40a52267377ca18b888c6798279aa83f1c6d1f8eb3ca61
license    : MIT
component  : programming.ruby
summary    : RubyGem - net-ssh
description: |
    Net::SSH: a pure-Ruby implementation of the SSH2 client protocol. It allows you to write programs that invoke and interact with processes on remote servers, via SSH2.
builddeps  :
    - pkgconfig(ruby-2.3)
rundeps    :
    - ruby
install    : |
    %gem_install
